// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB04cvj0TEdac1-wfHbMbmoCRTq4XVbg_U',
    appId: '1:393611506422:android:f864f79df7084de28972d7',
    messagingSenderId: '393611506422',
    projectId: 'sincro-3ac01',
    storageBucket: 'sincro-3ac01.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFR2VUKe4T3Va1BrNeItHiMnuz5CXpd0M',
    appId: '1:393611506422:ios:7653971e6eace4d78972d7',
    messagingSenderId: '393611506422',
    projectId: 'sincro-3ac01',
    storageBucket: 'sincro-3ac01.firebasestorage.app',
    iosBundleId: 'com.sincro.sincroMobile',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ9MdB2og4L2p1VTruiWsgwGP3VaqPZlE',
    appId: '1:393611506422:web:e23bba89ee34ae1e8972d7',
    messagingSenderId: '393611506422',
    projectId: 'sincro-3ac01',
    authDomain: 'sincro-3ac01.firebaseapp.com',
    storageBucket: 'sincro-3ac01.firebasestorage.app',
    measurementId: 'G-0J9SGTELC3',
  );
}
